### ISSUE TITLE
Color consistency on the site

### ISSUE THREAD

**Issue by AhmedQeshta** [GSG-G11/Team3-News#50]
### Color In your site

- first, color consistency
- On First Page, the color Navbar And Footer is not the best;
- On Second Page, the color section comments is not the best;

#### Resorces For Color 
1- [Brand Colors](https://brandcolors.net/) 
2- [image color picker](https://imagecolorpicker.com/)

**Comment by Mahmoud-Ahmad2** [comment]
We will take your advice in the next time
