### ISSUE TITLE
Animations and transitions In your Website

### ISSUE THREAD

**Issue by AhmedQeshta** [GSG-G11/Team3-News#54]
### Animations and transitions In your Website

It's nice to add effects to the site, but on your site animation durations is not the best, can see resource for more to become the best.

#### Resource
[animation duration](https://www.w3schools.com/cssref/css3_pr_animation-duration.asp)
[animations](https://www.w3schools.com/css/css3_animations.asp)

**Comment by Mahmoud-Ahmad2** [comment]
This issues is duplicated with #48
