### ISSUE TITLE
General Style on your Site (Font - Body)

### ISSUE THREAD

**Issue by AhmedQeshta** [GSG-G11/Team3-News#60]
#### First Comment Font On Your Site

1. on-site Font Family is not the best, you can use the font from [Google Font](https://fonts.google.com/).
2. Font Size on the body and on the navbar is not the best. 
3. Text above image does not appear good, can add a background for text , Can see this [Resources](https://www.w3schools.com/howto/howto_css_image_text.asp) and [this](https://www.w3schools.com/howto/howto_css_image_text_blocks.asp)

#### Second Comment Responsive
Check navbar responsive when the device has width 570px and less

**Comment by Mahmoud-Ahmad2** [comment]
Thank you for your feedback, but we think this is the best style for our website
